Pr branch
Atharva-77/To-do-list-React pull request #1
Opened 2022-09-30 05:39 UTC by Atharva-77

This is the code for review for PR. Do let me know

2022-10-13 06:50 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +              <BrowserRouter >
Move Router code in new component `Router.jsx`

2022-10-13 07:17 UTC, chandreshpatidar requested changes

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +
Remove these lines

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +import React,{useState} from 'react';
Add VS code extensions `Pretier, `

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +import MainPg from './Pages/Unused-Pages/MainPg';
Remove un-used components from entire repo

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +import MainDataPg from './Pages/MainDataPg';
Keep meaningful name

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +import { ColorContext } from './Components/Context'
Move context into `services -> context -> filename`

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +
Remove redundent blank line

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
>  function App() {
Use Arrow funtcion syntax

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +  const [empDetails,setempDetails]=useState([])
`setempDetails` reformat in case-case

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +        <ColorContext.Provider value= {{empDetails,setempDetails,allId,setallId}}>
Rename `ColorContext`

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +                         </Routes>
Reformat with prettier

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.js
> +                                                            <Heading />
Move ` <Heading />` outside of routes

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/Components/Context.js
> +import React,{useState} from 'react';
Move this file in services folder as explain in App.js file

Remove un-used variable.,
Import `createContext` as module

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.css
> +    --light-lessOpacity-green:#8ff5ffed;
Check this color code

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.css
>  :root
Format all files with prettier
Remove un-used css

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.css
> +.heading_Div
`heading_Div` -> `headingDiv`

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.css
> -    /* font-size: larger; */
Remove commented code

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/App.css
Remove redundant empty line

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/Components/Form.css
>  }
Add blank line between two classnames

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/Components/Form.js
> +import './Form.css'
Import css files at bottom/top of all import

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/Components/Form.js
> +
Remove blank line

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/Components/Form.js
> +//new compo for input fie;d
Remove these lines

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/Components/Form.js
> +
Remove commented code

2022-10-13 07:17 UTC, chandreshpatidar commented on to-do-list/src/Components/Form.js
> +                    <InputComponent className_Prop='inputTag' spanName="LastName" value_Prop={lastName} onChange_Prop={e=>lastNameFunc(e)} placeholder='Enter Last Name'/>
e=>lastNameFunc(e) -> `lastNameFunc`

2022-10-14 06:06 UTC, Atharva-77 commented
Closing this PR. Resolved the issues

2022-10-14 06:06 UTC, closed without merging